apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiR1YyYzJWeWF6cG5hSEJmTmxRelUydGphVlZtVkZKMVQxRkRkM1pCVFUwMGMwRTViR0p5VlRCVE1YcHdSM2RWIn19fQo=
type: kubernetes.io/dockerconfigjson
